### ISSUE TITLE
Error when using with `target-bigquery`

### ISSUE THREAD

**Issue by hack-c** [dluftspring/tap-hellobaton#8]
Hi there, I have installed `tap-hellobaton` and configured as in the README. Running into this error when using with `target-bigquery`. 
```
2022-02-09T21:33:19.248121Z [info     ] INFO activity schema: {'properties': {'id': {'type': 'integer'}, '_self': {'type': 'string'}, 'type': {'type': ['string', 'null']}, 'group': {'type': 'string'}, 'parent': {'type': ['string', 'null']}, 'child': {'type': ['string', 'null']}, 'actor': {'type': ['string', 'null']}, 'project': {'type': 'string'}, 'parent_type': {'type': ['string', 'null']}, 'child_type': {'type': ['string', 'null']}, 'meta': {'type': ['object', 'null']}, 'created': {'format': 'date-time', 'type': 'string'}, 'modified': {'format': 'date-time', 'type': 'string'}}} cmd_type=loader job_id=2022-02-09T213315--tap-hellobaton--target-bigquery name=target-bigquery run_id=6bffdd0c-cd23-4d24-8716-8ff330f4691f stdio=stderr
2022-02-09T21:33:19.758702Z [info     ] time=2022-02-09 16:33:19 name=tap-hellobaton level=INFO message=INFO METRIC: {'type': 'timer', 'metric': 'http_request_duration', 'value': 1.049385, 'tags': {'endpoint': '/activity/', 'http_status_code': 200, 'status': 'succeeded'}} cmd_type=extractor job_id=2022-02-09T213315--tap-hellobaton--target-bigquery name=tap-hellobaton run_id=6bffdd0c-cd23-4d24-8716-8ff330f4691f stdio=stderr
2022-02-09T21:33:19.759769Z [info     ] CRITICAL 'RECORD'              cmd_type=loader job_id=2022-02-09T213315--tap-hellobaton--target-bigquery name=target-bigquery run_id=6bffdd0c-cd23-4d24-8716-8ff330f4691f stdio=stderr
2022-02-09T21:33:19.761067Z [info     ] CRITICAL ['Traceback (most recent call last):\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/__init__.py", line 129, in main\n    for state in state_iterator:\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/process.py", line 54, in process\n    for s in handler.handle_record_message(msg):\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/processhandler.py", line 179, in handle_record_message\n    nr = format_record_to_schema(nr, self.bq_schema_dicts[stream])\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/schema.py", line 359, in format_record_to_schema\n    record[k] = conversion_dict[bq_schema[k]["type"]](v)\n', "KeyError: 'RECORD'\n"] cmd_type=loader job_id=2022-02-09T213315--tap-hellobaton--target-bigquery name=target-bigquery run_id=6bffdd0c-cd23-4d24-8716-8ff330f4691f stdio=stderr
2022-02-09T21:33:19.837095Z [error    ] Loading failed                 code=2 job_id=2022-02-09T213315--tap-hellobaton--target-bigquery message=CRITICAL ['Traceback (most recent call last):\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/__init__.py", line 129, in main\n    for state in state_iterator:\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/process.py", line 54, in process\n    for s in handler.handle_record_message(msg):\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/processhandler.py", line 179, in handle_record_message\n    nr = format_record_to_schema(nr, self.bq_schema_dicts[stream])\n', '  File "/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/loaders/target-bigquery/venv/lib/python3.8/site-packages/target_bigquery/schema.py", line 359, in format_record_to_schema\n    record[k] = conversion_dict[bq_schema[k]["type"]](v)\n', "KeyError: 'RECORD'\n"] name=meltano run_id=6bffdd0c-cd23-4d24-8716-8ff330f4691f
2022-02-09T21:33:19.837730Z [info     ] ELT could not be completed: Loader failed cmd_type=elt job_id=2022-02-09T213315--tap-hellobaton--target-bigquery name=meltano run_id=6bffdd0c-cd23-4d24-8716-8ff330f4691f stdio=stderr
2022-02-09T21:33:19.837932Z [info     ] For more detailed log messages, check the generated log file '/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/logs/elt/2022-02-09T213315--tap-hellobaton--target-bigquery/6bffdd0c-cd23-4d24-8716-8ff330f4691f/elt.log' or re-run the command using the '--log-level=debug' CLI flag. cmd_type=elt job_id=2022-02-09T213315--tap-hellobaton--target-bigquery name=meltano run_id=6bffdd0c-cd23-4d24-8716-8ff330f4691f stdio=stderr
ELT could not be completed: Loader failed
For more detailed log messages, check the generated log file '/Users/chack/Documents/engineering/meltano-projects/baton/.meltano/logs/elt/2022-02-09T213315--tap-hellobaton--target-bigquery/6bffdd0c-cd23-4d24-8716-8ff330f4691f/elt.log' or re-run the command using the '--log-level=debug' CLI flag.
2022-02-09T21:33:19.891566Z [error    ] Future exception was never retrieved
```

**Comment by hack-c** [comment]
On some further inspection, I believe this is related to this: https://github.com/RealSelf/target-bigquery/issues/10
```
I think the problem here is that the tap has created a schema which has ordered the type list in a way that target-bigquery does not expect i.e.'title': {'type': ['string', 'null']} when it expects 'title': {'type': ['null', 'string']}.
```

I've proposed a patch there but would it be possible to reorder the `'type':[...]` list that the tap outputs to put the `'null'` first ?

**Comment by marknotfound** [comment]
I think #9 should fix this but will see what @dluftspring thinks when he gets some time to review

**Comment by dluftspring** [comment]
Just catching up here.

It seems like a pretty big issue with the target to expect an ordered list for nullable / secondary types. I'm okay with merging the changes in #9  as long as something changes with the underlying target. I think most of the taps i've seen follow the convention `['primary_type', 'null']` so i'm surprised this is just impacting a few taps?

**Comment by dluftspring** [comment]
@hack-c can you try using this version of the target? https://github.com/adswerve/target-bigquery.

Meltano supports variants for all it s plugins but usually defaults to the most actively maintained ones on meltano hub. Unless there's a specific need to use the one that's causing the problem for other functionality you prefer.

**Comment by hack-c** [comment]
hey all, turns out we _were_ using adswerve's version. 
```
cat meltano.yml
...
  - name: target-bigquery
    variant: adswerve
    pip_url: git+https://github.com/adswerve/target-bigquery.git@0.11.3
...
```

**Comment by chrishenry** [comment]
I've been working through this on and off for a few days, and have filed an issue with `target-bigquery` https://github.com/adswerve/target-bigquery/issues/32

@hack-c one other option for you would be to exclude the activity stream. If you're using meltano, you can specify `--exclude activity.*`

**Comment by dluftspring** [comment]
@chrishenry we solved this by using the force fields option with adswerves bigquery target. You just have to cast any empty JSON fields to strings and then deal with them in the data warehouse. I'll close this issue once I have time to write up a note in the README. I also want to try and see if 'additionalProperties' fixes anything given that the issue is when an endpoint sends an empty JSON object.

**Comment by chrishenry** [comment]
Hey Dan, thanks for the quick response. I've been working on adding more fields to the activity.meta object, which changes the issue a little bit. In that case, `force_fields` probably won't work anymore. 

That said, I won't submit that PR until I have a resolution with target-bigquery.

**Comment by dluftspring** [comment]
Hm I haven't had time to test with BQ but theoretically there shouldn't be a problem coercing empty or populated JSON objects to strings using `force_fields` it's just not ideal because then you have to worry about downstream parsing errors. I thought #10 might work but haven't had a chance to test.
